# Generated by Django 5.0.7 on 2024-08-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_professionals_portfolio_portfolios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionals',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/banners'),
        ),
    ]
