# Generated by Django 5.0.7 on 2024-08-05 09:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_professionals_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='adminusers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materials',
            name='discount_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='mobileusers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='proreview',
            constraint=models.UniqueConstraint(fields=('created_by', 'professional'), name='unique_created_by_professional'),
        ),
        migrations.AddField(
            model_name='booksreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.books'),
        ),
        migrations.AddField(
            model_name='booksreview',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_reviews', to='core.mobileusers'),
        ),
        migrations.AddField(
            model_name='materialsreview',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='material_reviews', to='core.mobileusers'),
        ),
        migrations.AddField(
            model_name='materialsreview',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.materials'),
        ),
        migrations.AddConstraint(
            model_name='booksreview',
            constraint=models.UniqueConstraint(fields=('created_by', 'book'), name='unique_created_by_book'),
        ),
        migrations.AddConstraint(
            model_name='materialsreview',
            constraint=models.UniqueConstraint(fields=('created_by', 'material'), name='unique_created_by_material'),
        ),
    ]
