# Generated by Django 5.0.7 on 2024-08-05 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booksreview_materialsreview_alter_adminusers_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='discount_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
