# Generated by Django 5.0.7 on 2024-08-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_books_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], max_length=100),
        ),
    ]
