# Generated by Django 5.0.7 on 2024-08-06 06:16

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_transactions_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('other', 'Other')], default='home', max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('pincode', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(999999)])),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=300)),
                ('flat_no', models.CharField(max_length=300)),
                ('landmark', models.CharField(blank=True, max_length=500, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adressses', to='core.mobileusers')),
            ],
        ),
    ]
