# Generated by Django 5.0.7 on 2024-08-06 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='date_time',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='addresses',
            name='pincode',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
