# Generated by Django 5.0.7 on 2024-08-08 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_date_time_transactions_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proreview',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.professionals'),
        ),
    ]
