# Generated by Django 5.0.7 on 2024-08-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_addresses_created_on_addresses_last_edited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolios',
            name='image',
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='professionals/portfolios')),
                ('caption', models.CharField(blank=True, max_length=250, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.portfolios')),
            ],
        ),
    ]
