# Generated by Django 5.0.7 on 2024-08-12 06:54

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_portfolios_image_alter_portfolios_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileusers',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region='IN', unique=True),
        ),
    ]
