# Generated by Django 5.0.7 on 2024-08-12 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_mobileusers_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='core.professionals'),
        ),
    ]
