# Generated by Django 5.0.7 on 2024-08-06 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_rename_date_time_transactions_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('professional', 'Professional'), ('book', 'Book'), ('material', 'Material')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.mobileusers')),
            ],
            options={
                'unique_together': {('user', 'type', 'item_id')},
            },
        ),
    ]
